### ISSUE TITLE
The code inside "Episode 4 - Deciding Package Structure" should follow the flow.

### ISSUE THREAD

**Issue by radifar** [MolSSI-Education/python-package-best-practices#25]
The code inside Episode 4 doesn't reflect the `starting_notebook.ipynb`, as @khoivan88 pointed out at #11. I think it is important for the student/reader to follow along the code in the consistent manner since the differences will distract and derail the flow of the learning path. Imagine when the student/reader got confused which one should they follow, or asking why they are different? Or maybe when they use the code that have descriptive variable name then they reach Episode 5 and can not practice the `Variable Names` lesson.

Also, it is important to highlight that Episode 4 is the continuation of `Using Branches - exercise` from [Episode 2](http://education.molssi.org/python-package-best-practices/02-git/index.html). Therefore there should be a note near the `Package Structure` header that warn the student/reader that they should have completed the `Using Branches - exercise` from Episode 2.

PS. I think using [prereq blockquote](https://carpentries.github.io/lesson-example/04-formatting/index.html#prereq) would be appropriate at the beginning of Episode 4 :)

**Comment by janash** [comment]
Thanks for highlighting the issue with the code inconsistency.  This needs to be fixed in Episode 4 ( I believe initially episodes 4 and 5 were switched, so the code in 4 was after coding style had been fixed). As they are not dependent on one another, one way to fix this is to switch 4 and 5 again.

As for the comment on Episode 2 being a prerequisite of Episode 4, this workshop is designed to be done in order of episodes, so you should always complete previous episodes before this one. I don't see it as necessary to say previous episodes are a prerequisite, but there is also no harm in it.

Can you submit a PR making these changes?

**Comment by radifar** [comment]
Yes I think it will be more make sense to switch episodes 4 and 5 because episode 5 is more fundamental.

I will be honest with you Dr. Nash, sometimes I have the urge to skip the exercise. Most of the time I see exercise/homework as supplemental and not mandatory XD. I am not the only one who think this way right?

Alright Dr. Nash, I will submit the PR.

**Comment by janash** [comment]
That's fair about the exercises :) It is probably a good idea to state that you need to do them when they are necessary for following along (sometimes they are not).
