### ISSUE TITLE
CITATION 

### ISSUE THREAD

**Issue by BatoolMM** [MolSSI-Education/python-package-best-practices#40]
Hi, 

I'm giving a workshop as a part of WiDS2021 and I am wondering if I can use some episodes (e.g. GitHub, ..) from this lesson to incorporate it in the tutorials. I understand that this lesson is made available under the Creative Commons Attribution license but what is the appropriate way of citing it. I looked into `CITATION` file but it's empty. Can you advise me of the best way of using the materials, giving credits to the authors and citing them, please?

**Comment by janash** [comment]
Hi! I have been trying to find this in my email but was unable to. I'm glad I found it on the issues.

Please just link the github repo and/or the lesson website - http://education.molssi.org/python-package-best-practices/ and mention "The Molecular Sciences Software Institute"

It could be something like

"This workshop has activities based on episodes from the workshop 'Best Practices in Python Package Development' by The Molecular Sciences Software Institute. Lessons can be found here *link*"

I will check if there is a different way to cite, but unless I indicate otherwise I think this will work. Let me know if you would like to discuss logistics or strategies before your workshop

**Comment by BatoolMM** [comment]
Thank you Jessica, 

I love the way this course was designed and I'm sure others will love to re-use the material especially it's under CC-BY licence.  It would be nice if there is a DOI generated for the repository using Zenodo. It makes it way easier to cite when the materials are used. 

I actually went ahead (and really sorry for that) and used the part about git in the workshop. I mentioned both the link and title of the workshop 'Best Practices in Python Package Development'  and "The Molecular Sciences Software Institute" in four places in the workshop
1- The `README.MD` file
2- the `AUTHORS` file
3- The introduction of the workshop in the `index.md`
4- After the same section of the part I took from the lesson, all inside `_episodes.md`. I mentioned it in **bold** after each section.

This is the link to the [repository](https://github.com/BatoolMM/Collaborating-on-Open-Data-Science-Projects) and this is the link to [the website](https://batoolmm.github.io/Collaborating-on-Open-Data-Science-Projects/). Thank you again.

**If anything I did wasn't correct or not properly cited, please let me know and I'll correct it immediately.**

**Comment by janash** [comment]
We're glad that you like the course and we're always happy to see our materials used!

I am looking into DOI options for the materials and will let you know if we get something.

**Comment by janash** [comment]
Hi @BatoolMM - we've added a DOI and citation information to [CITATION](https://github.com/MolSSI-Education/python-package-best-practices/blob/gh-pages/CITATION). Thank you for the suggestion!

**Comment by BatoolMM** [comment]
Thank you 😊
