### ISSUE TITLE
Add citation.cff file

### ISSUE THREAD

**Issue by janash** [MolSSI-Education/python-package-best-practices#54]
GitHub recently added built in citation support to repos (https://twitter.com/natfriedman/status/1420122675813441540) . This requires the addition of a file called `CITATION.cff`. `cff` stands for `citation file format` (https://citation-file-format.github.io/).

This should be added to the repo for the next release.

**Comment by radifar** [comment]
I took a quick look on that page, and also the official doc on GitHub [here](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files#about-citation-files). It turns out that there is already a CITATION file that is used by this repo as the citation information. The problem is that GitHub is unable to parse the CITATION file and instead let us view the file.

Maybe we can use that file as the starting point and input the data to [cffinit](https://citation-file-format.github.io/cff-initializer-javascript/), then add the new contributors to the cff.

**Comment by janash** [comment]
Yes, definitely. We should use the existing CITATION file. I still need to add you (@radifar) and Eric (@eirrgang), but I haven't gotten around to it yet :) Planning to update the citation, then make a release. Thanks for the links showing tools to use for this.

**Comment by janash** [comment]
Closed by 
#75
